version: '3.3'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mydb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Prueba2
      MYSQL_USER: miguelsilvetti
      MYSQL_PASSWORD: miguel8204
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
